### ISSUE TITLE
extend the `update_provided_persons` flow to all entity types

### ISSUE THREAD

**Issue by sennierer** [InTaVia/prefect-flows#19]
we need provided entities (those linking all entities referencing the same real world entity to one common node in the intavia.eu namespace) for all entities (persons, groups, places, CHO, events?).
The flow should follow the sameAs links provided by other flows to link as much entities as possible.

**Comment by yoge1** [comment]
As we already have Provided_Person instances in the source data (at least in BS and BNet) we need to take this into account, i.e. use information provided by them when linking Person_Proxy instances to shared Provided_Person instances by the flow.

**Comment by yoge1** [comment]
> As we already have Provided_Person instances in the source data (at least in BS and BNet) we need to take this into account, i.e. use information provided by them when linking Person_Proxy instances to shared Provided_Person instances by the flow.

This has been implemented in https://github.com/InTaVia/prefect-flows/commit/817fd9c4e07c43abd31f249a4dd81acd22349ba4
